services:
  formsmenu-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: formsmenu-frontend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped